# Generated by Django 6.0.5 on 2026-05-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
